### PR TITLE
increment version

### PR DESCRIPTION
**Pull request by shahednasser**
Incrementing the version of the template following the change in PR #3

### CODE REVIEW

**Comment by shahednasser** [comment]
@Deathwish98 can you push a new version of the template when possible? 🙏🏻

**Comment by SharmaPawan11** [comment]
@shahednasser I haven't pushed the template on `npm`. We are only referencing it using git url : 

`npx create-strapi-app strapi-medusa --template <User>/strapi-medusa-template.git`

**Comment by shahednasser** [comment]
I think the problem is that it's overlapping with [this npm package](https://www.npmjs.com/package/medusa-strapi). So, Strapi on installation is detecting an NPM package because of `package.json` and trying to install it. This can be resolved by either removing `package.json` or renaming the package. Should I create a PR for it and which approach do you prefer?

**Comment by SharmaPawan11** [comment]
Ah Sorry, I haven't getting any time lately to follow up with the development related to the plugin or support the medusa community. Would help a lot if you create a PR for it .

**Comment by shahednasser** [comment]
Seems like the only way to fix this is either to publish a new package or update the existing template. @Kyle772 would it be possible to update your forked GitHub repository with the changes in this one and publish a new version of the NPM package? Otherwise, I would have to publish a new NPM package

**Pull request merged**
